apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-website-frontend
  template:
    metadata:
      labels:
        app: personal-website-frontend
    spec:
      containers:
      - name: front-end
        image: benldouthwaite/personal-website:dev
        ports:
        - containerPort: 8080
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: personal-website-frontend # Name of the kubernetes resource
spec:
  type: NodePort               # Exposes the service by opening a port on each node
  selector:
    app: personal-website-frontend     # Any Pod matching the label `app=polling-app-client` will be picked up by this service
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30001
    protocol: TCP