apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-website-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-website-frontend
  template:
    metadata:
      labels:
        app: personal-website-frontend
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: personal-website-frontend
        image: benldouthwaite/personal-website:v0.0.22
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
---
apiVersion: v1                  # API version
kind: Service                   # Type of kubernetes resource
metadata:
  name: personal-website-frontend-svc # Name of the kubernetes resource
spec:
  selector:
    app: personal-website-frontend     # Any Pod matching the label `app=polling-app-client` will be picked up by this service
  ports:                        # Forward incoming connections on port 80 to the target port 80 in the Pod
  - name: http
    port: 8080
    targetPort: 8080